[package]
name = "json-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11"] }
egui = { version = "0.27.2", default-features = false, features = [] }
egui_extras = { version = "0.27.2", default-features = false, features = [] }
json-flat-parser = {git = "https://github.com/nmeylan/json-parser-flat-format.git", rev = "b6b61be", features = ["indexmap", "simdutf8"]}

#[patch."https://github.com/nmeylan/json-parser-flat-format.git"]
#json-flat-parser = {path = "/home/nmeylan/dev/ragnarok/json-flat-parser"}