[package]
name = "json-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11"] }
egui = { version = "0.27.2", default-features = false, features = [] }
egui_extras = { version = "0.27.2", default-features = false, features = [] }
simdutf8 = "0.1.4"

#[patch."https://github.com/nmeylan/text-editor"]
#text-editor = {path = "/home/nmeylan/dev/perso/text-editor"}