[package]
name = "json-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
egui_glow = "0.27.2"
egui = "0.27.2"
egui_extras = "0.27.2"
serde_json = "1.0"
text-editor = {git = "https://github.com/nmeylan/text-editor", rev = "5808089"}

#[patch."https://github.com/nmeylan/text-editor"]
#text-editor = {path = "/home/nmeylan/dev/perso/text-editor"}